export const metadata = {
	title: 'G-Clone',
};

export default function Head() {

	return (
		<>
			<title>G-Clone</title>
			<meta content="width=device-width, initial-scale=1" name="viewport"/>
			<meta content="G-Clone Generated by NextJS 13" name="description"/>
			<link rel="icon" href="favicon.ico"/>
		</>
	);
}
