import './globals.css'
import React, {ReactNode} from "react";
import {Footer} from "@/components";


export const metadata = {
  title: 'GClone',
  description: 'GClone Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {

  return (
    <html lang="en">
      <body>
        <main>
            {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
