import './globals.css'
import React, {ReactNode} from "react";


export const metadata = {
  title: 'GClone',
  description: 'GClone Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
