import {SearchHeader} from "@/components";
import React, {FC, ReactNode} from "react";

export const metadata = {
	title: 'GClone',
	description: 'GClone Generated by create next app',
}

const SearchLayout: FC<{ children: ReactNode }> = ({children}) => {
	return (
		<>
			<SearchHeader/>
			{children}
		</>
	)
}
export default SearchLayout;
